// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyilnNcJI9teVCZw-tFGbQmyrR94kkbuI',
    appId: '1:495632436565:web:5efddcf395ea80e28173dc',
    messagingSenderId: '495632436565',
    projectId: 'vibra-3f307',
    authDomain: 'vibra-3f307.firebaseapp.com',
    storageBucket: 'vibra-3f307.firebasestorage.app',
    measurementId: 'G-1JGPKWJZJ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyFoRqS8VbulG-wx16pWyj7F_VJoB50LM',
    appId: '1:495632436565:android:e3cf0cccacd849918173dc',
    messagingSenderId: '495632436565',
    projectId: 'vibra-3f307',
    storageBucket: 'vibra-3f307.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9V3kB42eLnyPZRkHuK111iyiszQB4Ogw',
    appId: '1:495632436565:ios:bca8764257acbfba8173dc',
    messagingSenderId: '495632436565',
    projectId: 'vibra-3f307',
    storageBucket: 'vibra-3f307.firebasestorage.app',
    iosBundleId: 'com.vibra.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9V3kB42eLnyPZRkHuK111iyiszQB4Ogw',
    appId: '1:495632436565:ios:6967134f9cb575138173dc',
    messagingSenderId: '495632436565',
    projectId: 'vibra-3f307',
    storageBucket: 'vibra-3f307.firebasestorage.app',
    iosBundleId: 'com.example.vibra',
  );
}
